apps/apis/urls.py
from django.conf.urls import url
from  .views import comment,community
urlpatterns = [
    url(r'^comment$',comment,name='comment'),
    url(r'^community$',community,name='community'),


]

apps/user/urls.py
from django.conf.urls import url
from  .views import Register,user_login,user_logout
urlpatterns = [
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^register/$', Register.as_view(), name='register'),
]

recipe/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from apps.user.views import submit,test
from apps.index.views import index,search,detail,add_collection
from apps.video.views import video
from apps.news.views import news
from apps.comment.views import community
from apps.shop.views import shop
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index,name='index'), # 首页
    url(r'^user/', include('apps.user.urls', namespace='user')), # 用户模块
    url(r'^shop/',include('apps.shop.urls',namespace='shop')), #商品模块

    url(r'^submit$',submit,name='submit'),

    url(r'^search/',search,name='search'),
    url(r'^detail/',detail,name='detail'),

    url(r'^video/',video,name='video'),

    url(r'^news/',news,name='news'),




    url(r'^add_collection$',add_collection,name='add_collection'),
    url(r'^test$',test,name='test'),
    url(r'^community/',community,name='community'),

    url('ckeditor',include('ckeditor_uploader.urls')),
    url(r'api/v1/',include('apps.apis.urls',namespace="apis")),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

apps/news/views.py
from bs4 import BeautifulSoup
from django.shortcuts import render
import requests
# Create your views here.
from django.views.decorators.cache import cache_page
@cache_page(60 * 15)
def news(request):
    news = news_spider()
    soup = get_soup()
    if not request.GET.get("id"):
        id = 0
    else:
        id = int(request.GET.get("id"))-1
    detail_link = soup.select('div.detail a')[id]['href']
    soup = get_soup(detail_link)
    contents = soup.select('div.content p')
    #print(contents)
    content=" ".join(repr(i) for i in contents)
    #print(content)
    return render(request, "news.html", locals())



def get_soup(url = 'https://www.meishichina.com/News/'):

    header = {'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 \
    (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36'}

    res = requests.get(url=url, headers= header)
    res.encoding = 'utf-8'
    soup = BeautifulSoup(res.text, 'html.parser')
    return soup

def news_spider():
    soup = get_soup()
    k=[]
    titles = soup.select('div.detail a')
    for i in titles[:20]:
        k.append(i.get_text())

    v=[]
    contents = soup.select('div.detail p')[:40]
    for i,j in enumerate(contents):
        if i % 2 == 0:
            content = contents[i].get_text() + " "*4 + contents[i+1].get_text() + "..."
            v.append(content)

    news = dict(zip(k,v))
    return news

apps/index/templates/base.html
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<!-- Basic Page Needs
================================================== -->
<meta charset="utf-8">
<title>Chow</title>

<!-- Mobile Specific Metas
================================================== -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{#    video css  #}

{#<!--布局样式，意义不大-->#}
<link rel="stylesheet" href="/static/css/demo.css">
{#    video css  #}
<!-- CSS
================================================== -->

<link rel="stylesheet" href="/static/css/style.css">
<link rel="stylesheet" href="/static/css/colors/green.css" id="colors">
<script type="text/javascript" src="/static/scripts/jquery-1.11.0.min.js"></script>

<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body>

<!-- Wrapper -->
<div id="wrapper">


<!-- Header
================================================== -->
<header id="header">

<!-- Container -->
<div class="container">

	<!-- Logo / Mobile Menu -->
	<div class="three columns">
		<div id="logo">
			<h1><a href="{% url "index" %}"><img src="/static/images/logo.png" alt="Chow" /></a></h1>


		</div>
	</div>


<!-- Navigation
================================================== -->
<div class="thirteen columns navigation">

	<nav id="navigation" class="menu nav-collapse">
		<ul>

			<li><a href="{% url 'index' %}" id="{% if request.path == "/" %}current{% endif %}" >主页</a></li>

            <li><a href="{%  url  'video' %}" id="{% if request.path == "/video" %}current{% endif %}">美食视频</a></li>

            <li><a href="{%  url  'community' %}" id="{% if request.path == "/community" %}current{% endif %}">美食社区</a></li>

            <li><a href="{%  url  'shop:index' %}" id="{% if request.path == "/shop" %}current{% endif %}">美食商店</a></li>

            <li><a href="{% url "news" %}" id="{% if request.path == "/news" %}current{% endif %}">美食资讯</a></li>

			<li><a href="{%  url  'search' %}" id="{% if request.path == "/search" %}current{% endif %}">美食搜索</a></li>



			<li><a href="#">你好,{{ user }}</a>
				<ul>


                    <li><a href="{%  url "submit"  %}">个人中心</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{%  url "user:logout"  %}">登出</a></li>
                    {% else %}
                        <li><a href="{%  url "user:login"  %}">登录</a></li>
                        <li><a href="{%  url "user:register"  %}">注册</a></li>
                    {% endif %}



				</ul>
			</li>
		</ul>
	</nav>

</div>


</div>
<!-- Container / End -->
</header>

    {% block body  %}{% endblock %}



</div>
<!-- Wrapper / End -->


<!-- Footer
================================================== -->
<div id="footer">

	<!-- Container -->
	<div class="container">

		<div class="ten columns">
			<!-- Headline -->
			<h3 class="headline footer">关于</h3>
			<span class="line"></span>
			<div class="clearfix"></div>
			<p>数据均来源于网络,仅供学习使用,不用做任何商业用途</p>
		</div>





		<div class="five columns">

			<!-- Headline -->
			<h3 class="headline footer">通讯</h3>
			<span class="line"></span>
			<div class="clearfix"></div>
			<p>本人电话:13135135960</p>
			<p>本人QQ:565539277</p>

			<form action="#" method="get">
				<input class="newsletter" type="text" placeholder="565539277@qq.com" value=""/>
				<button class="newsletter-btn" type="submit">订阅</button>

			</form>
		</div>

	</div>
	<!-- Container / End -->

</div>
<!-- Footer / End -->

<!-- Footer Bottom / Start -->
<div id="footer-bottom">

	<!-- Container -->
	<div class="container">

		<div class="eight columns">© Copyright 2020 by <a href="#">lirixiang</a>版权所有</div>

	</div>
	<!-- Container / End -->

</div>
<!-- Footer Bottom / End -->

<!-- Back To Top Button -->
<div id="backtotop"><a href="#"></a></div>



<!-- Java Script
================================================== -->
<script src="/static/scripts/jquery-1.11.0.min.js"></script>
<script src="/static/scripts/jquery-migrate-1.2.1.min.js"></script>
<script src="/static/scripts/jquery.superfish.js"></script>
<script src="/static/scripts/jquery.royalslider.min.js"></script>
<script src="/static/scripts/responsive-nav.js"></script>
<script src="/static/scripts/hoverIntent.js"></script>
<script src="/static/scripts/isotope.pkgd.min.js"></script>
<script src="/static/scripts/chosen.jquery.min.js"></script>
<script src="/static/scripts/jquery.tooltips.min.js"></script>
<script src="/static/scripts/jquery.magnific-popup.min.js"></script>
<script src="/static/scripts/jquery.pricefilter.js"></script>
<script src="/static/scripts/custom.js"></script>


<!-- Style Switcher
================================================== -->
<script src="/static/scripts/switcher.js"></script>

<div id="style-switcher">
	<h2>Style Switcher <a href="#"></a></h2>

	<div>
		<h3>Predefined Colors</h3>
		<ul class="colors" id="color1">
			<li><a href="#" class="green" title="Green"></a></li>
			<li><a href="#" class="blue" title="Blue"></a></li>
			<li><a href="#" class="orange" title="Orange"></a></li>
			<li><a href="#" class="navy" title="Navy"></a></li>
			<li><a href="#" class="yellow" title="Yellow"></a></li>
			<li><a href="#" class="peach" title="Peach"></a></li>
			<li><a href="#" class="beige" title="Beige"></a></li>
			<li><a href="#" class="purple" title="Purple"></a></li>
			<li><a href="#" class="celadon" title="Celadon"></a></li>
			<li><a href="#" class="pink" title="Pink"></a></li>
			<li><a href="#" class="red" title="Red"></a></li>
			<li><a href="#" class="brown" title="Brown"></a></li>
			<li><a href="#" class="cherry" title="Cherry"></a></li>
			<li><a href="#" class="cyan" title="Cyan"></a></li>
			<li><a href="#" class="gray" title="Gray"></a></li>
			<li><a href="#" class="darkcol" title="Dark"></a></li>
		</ul>

	</div>

	<div id="reset"><a href="#" class="button color">Reset</a></div>

</div>


</body>

</html>

apps/index/templates/index.html
{% extends "base.html" %}
{% block body %}
<section id="titlebar">
	<!-- Container -->
	<div class="container">

		<div class="eight columns">
			<h2>Index</h2>
		</div>

		<div class="eight columns">
			<nav id="breadcrumbs">
				<ul>
					<li>你在:</li>
					<li><a href="{% url "index" %}">主页</a></li>
				</ul>
			</nav>
		</div>

	</div>
	<!-- Container / End -->
</section>
<!-- Slider
================================================== -->






<!-- Content
================================================== -->
<div class="container">
  <iframe name="weather_inc" src="http://i.tianqi.com/index.php?c=code&id=1" width="330" height="35"
                frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
    <div id="homeSlider" class="royalSlider rsDefaultInv">

    {% for k in recommend %}
    <!-- Slide #1 -->
	<div class="rsContent">
        <a class="rsImg" href="{{ k.image_url }}"></a>
		<i class="rsTmb">{{ k.title }}</i>

		<!-- Slide Caption -->
		<div class="SlideTitleContainer rsABlock">
		<div class="CaptionAlignment">
			<div class="rsSlideTitle tags">
				<ul>
					<li>{{ k.series }}</li>
				</ul>
				<div class="clearfix"></div>
			</div>

            <h2 class="rsSlideTitle title"><a href="{%url "detail" %}?id={{ k.id }}">{{ k.title }}</a></h2>
            <p style="color: #fff;width: 1000px">{{ k.p }}</p>

			<div class="rsSlideTitle details">
				<ul>
					<li><i class="fa fa-cutlery"></i> {{ k.comment }}</li>
					<li><i class="fa fa-clock-o"></i> {{ k.likes }}</li><br>
					<li> 工艺:{{ k.flavor }}</li>
					<li> 口味:{{ k.technology }}</li>
{#					<li><i class="fa fa-user"></i> by <a href="#">{{ k.contributor }}</a></li>#}
				</ul>
			</div>

			<a href="{%url "detail" %}?id={{ k.id }}" class="rsSlideTitle button">了解详情</a>
		</div>
		</div>
	</div>
{% endfor %}

	</div>

	<!-- Masonry -->

    <div class="five column w705 overflow fl">

        <script type="text/javascript" src="/static/js/koala.min.1.5.js"></script>
        <div id="fsD1" class="focus">
            <div id="D1pic1" class="fPic">
                {% for i in image_urls %}
                <div class="fcon" style="display: none;">
                   <img src="{{ i }}" style="opacity: 1; width: 700px;height:400px;">
                </div>
                 {% endfor %}
            </div>
            <div class="fbg">
                <div class="D1fBt" id="D1fBt">
                    <a href="javascript:void(0)" hidefocus="true" target="_self" class=""></a>
                    <a href="javascript:void(0)" hidefocus="true" target="_self" class=""></a>
                    <a href="javascript:void(0)" hidefocus="true" target="_self" class=""></a>
                    <a href="javascript:void(0)" hidefocus="true" target="_self" class=""></a>
                </div>
            </div>
            <span class="prev"></span>
            <span class="next"></span>
        </div>
        <script type="text/javascript">
            Qfast.add('widgets', {path: "/static/js/terminator2.2.min.js", type: "js", requires: ['fx']});
            Qfast(false, 'widgets', function () {
                K.tabs({
                    id: 'fsD1',   //焦点图包裹id
                    conId: "D1pic1",  //** 大图域包裹id
                    tabId: "D1fBt",
                    tabTn: "a",
                    conCn: '.fcon', //** 大图域配置class
                    auto: 1,   //自动播放 1或0
                    effect: 'fade',   //效果配置
                    eType: 'click', //** 鼠标事件
                    pageBt: true,//是否有按钮切换页码
                    bns: ['.prev', '.next'],//** 前后按钮配置class
                    interval: 3000  //** 停顿时间
                })
            })
        </script>

    </div>
    <!-- Sidebar
================================================== -->
<div class="four columns">

	<!-- Search Form -->
	<div class="widget search-form">
		<nav class="search">
			<form action="{% url "search" %}" method="get">
                {% csrf_token %}
				<button><i class="fa fa-search"></i></button>
				<input class="search-field" type="text" placeholder="搜寻美食..." value="" name="q"/>
			</form>
		</nav>
		<div class="clearfix"></div>
	</div>




	<!-- Popular Recipes -->
	<div class="widget">
{#		<h4 class="headline">排行榜</h4>#}
{#		<span class="line margin-bottom-30"></span>#}
{#		<div class="clearfix"></div>#}

{#		<!-- Recipe #1 -->#}
{#        {% for i in ranking  %}#}
{#		<a href="{%url "detail" %}?id={{ i.id }}" class="featured-recipe">#}
{#            <img src="{{ i.image_url }}" alt="">#}
{#			<div class="featured-recipe-content">#}
{#				<h4> {{ forloop.counter }} {{ i.title }}</h4>#}
{#			</div>#}
{#			<div class="post-icon"></div>#}
{#		</a>#}
{#        {% endfor %}#}
        <div class="eight columns">
		<h3 class="headline">排行榜</h3><span class="line margin-bottom-3-"></span><div class="clearfix"></div>

		<!-- Tabs Navigation -->
		<ul class="tabs-nav">
            {% for i in ranking  %}
			<li ><a href="{% url "detail" %}?id={{ i.id }}">{{ forloop.counter }}.{{ i.title }}</a></li>
             {% endfor %}
		</ul>

	<br>
	</div>


		<div class="clearfix"></div>
	</div>


</div>
<div class="sixteen columns">
		<!-- Headline -->
 		<h3 class="headline">最新菜谱</h3>
		<span class="line rb margin-bottom-35"></span>
		<div class="clearfix"></div>

		<!-- Isotope -->
		<div class="isotope">
            {% for i in rand  %}
			<!-- Recipe #1 -->
			<div class="four recipe-box columns">

				<!-- Thumbnail -->
				<div class="thumbnail-holder">
					<a href="{%url "detail" %}?id={{ i.id }}">
						<img src="{{ i.image_url }}" alt=""/>
						<div class="hover-cover"></div>
						<div class="hover-icon">查看菜谱</div>
					</a>
				</div>

				<!-- Content -->
				<div class="recipe-box-content">
					<h3><a href="?">{{ i.title }}</a></h3>

					<div class="rating five-stars">
{#						<div class="star-rating"></div>#}
{#						<div class="star-bg"></div>#}
                        <h6>{{ i.comment }}评论</h6>
                         <div class="comment">
                            <span>..</span>0
                         </div>

                    </div>

					<div class="recipe-meta"><i class="like {{ i.id }}" id="{{ i.id }}">&#10084;</i> {{ i.likes }}</div>

					<div class="clearfix"></div>
				</div>
			</div>
            {% endfor %}


		</div>
		<div class="clearfix"></div>



	</div>





</div>
<!-- Container / End -->
 <script>
            $(".like").click(function () {
                console.log(id);
                 $.ajax({
                url: "{% url 'add_collection' %}",
                type:'GET',
                cache:false,
                success:function(data){
                   console.log(data);
                    $(".like"+id ).attr('class','cs');

                },
                error:function(xhr){
                    console.log(xhr);
                }

            });
            return false
        })

    </script>
<div class="margin-top-5"></div>

{% endblock %}

apps/index/templates/news.html
{% extends "base.html" %}
{% block body %}
<!-- Container -->
<div class="container">

	<!-- Accordion
	================================================== -->

	<div class="eleven columns">
		<h3 class="headline">最热资讯</h3><span class="line margin-bottom-35"></span><div class="clearfix"></div>

			<!-- Accordion -->
			<div class="accordion">

				<!-- Section 1 -->
                {% for k,v in news.items %}
				<h3><span class="ui-accordion-header-icon ui-icon ui-accordion-icon"></span>{{ forloop.counter }}&emsp;{{ k }}</h3>
				<div>
					<a href="{% url "news_detail" %}?id={{ forloop.counter }}"><p>{{ v }}</p></a>
				</div>
                {% endfor %}
			</div>
			<!-- Accordion / End -->
	</div>







</div>
<!-- Container / End -->


<div class="margin-top-40"></div>



{% endblock %}

apps/index/templates/recipe-page.html
{% extends "base.html" %}
{% block body %}
<!-- Recipe Background -->
<div class="recipeBackground">
	<img src="/static/images/recipeBackground.jpg" alt="" />
</div>


<!-- Content
================================================== -->
<div class="container" itemscope itemtype="http://schema.org/Recipe">

	<!-- Recipe -->

	<div class="ten columns">
	<div class="alignment">

		<!-- Header -->
		<section class="recipe-header">
			<div class="title-alignment">
				<h2>{{ item.title }}</h2>
{#				<div class="rating five-stars">#}
{#					<div class="star-rating"></div>#}
{#					<div class="star-bg"></div>#}
{#				</div>#}
				<span><a href="#reviews"></a></span>
			</div>
		</section>


		<!-- Slider -->
		<div class="recipeSlider rsDefault">
		    <img itemprop="image" class="rsImg" src="{{ item.image_url }}" alt="" />

		</div>


		<!-- Details -->
		<section class="recipe-details" itemprop="nutrition">
			<ul>
				<li>点赞: <strong itemprop="recipeYield">{{ item.likes }}</strong></li>
				<li>评论: <strong itemprop="prepTime">{{ item.comment }}</strong></li>
				<li>标签: <strong itemprop="cookTime">{{ item.series }}</strong></li>
			</ul>
			<a href="#" class="print"><i class="fa fa-print"></i>喜欢</a>
			<div class="clearfix"></div>
		</section>


		<!-- Text -->
		<p itemprop="description">{{ p }}</p>
          </div>
        </div>
         <div class="four column">
        <!-- Ingredients -->
		<h3>用料</h3>
		<ul class="ingredients">

            {% for k,v in main.items %}
			<li>

				主料{{ forloop.counter }}:&emsp;{{ v }}
			</li>
            {% endfor %}
            {% for i in aux %}
            <li>

			辅料{{ forloop.counter }}:&emsp;{{ i }}
			</li>
            {% endfor %}
		</ul>
        </div>


        <div class="ten column">
		<!-- Directions -->
		<h3>做法</h3>
		<ol class="directions" itemprop="recipeInstructions">
            {% for k,v in mea.items %}<br>
			{{ k }}
            <div style="width: 400px; border: 1px solid #000; height: auto;">
            <img  src="{{ v }}" style="width: 380px; margin: 10px;" alt="">
            </div>

            {% endfor %}
        {% for i in mea_tip %}
            {{ i }}<br>
        {% endfor %}
		</ol>
        </div>

{#		<!-- Share Post -->#}
{#		<ul class="share-post">#}
{#			<li><a href="#" class="facebook-share">Facebook</a></li>#}
{#			<li><a href="#" class="twitter-share">Twitter</a></li>#}
{#			<li><a href="#" class="google-plus-share">Google Plus</a></li>#}
{#			<li><a href="#" class="pinterest-share">Pinterest</a></li>#}
{##}
{#			<!-- <li><a href="#add-review" class="rate-recipe">Add Review</a></li> -->#}
{#		</ul>#}
		<div class="clearfix"></div>


		<!-- Meta -->
<!--  		<div class="post-meta">
			By <a href="#" itemprop="author">Sandra Fortin</a>, on
			<meta itemprop="datePublished" content="2014-30-10">30th November, 2014</meta>
		</div>  -->


		<div class="margin-bottom-40"></div>


		<!-- Headline -->
 		<h3 class="headline">你或许喜欢</h3>
		<span class="line margin-bottom-35"></span>
		<div class="clearfix"></div>

		<div class="related-posts">
            {% for i in recommend %}
		<!-- Recipe #1 -->
			<div class="four recipe-box columns">
				<!-- Thumbnail -->
				<div class="thumbnail-holder">
					<a href="{% url "detail" %}?id={{ i.id }}">
						<img src="{{ i.image_url }}" alt=""/>
						<div class="hover-cover"></div>
						<div class="hover-icon">查看</div>
					</a>
				</div>

				<!-- Content -->
				<div class="recipe-box-content">
					<h3><a href="#">{{ i.title }}</a></h3>
					<div class="recipe-meta">{{ i.likes }}</div>

					<div class="clearfix"></div>
				</div>
			</div>
  {% endfor %}
        </div>



		<div class="clearfix"></div>


		<div class="margin-top-15"></div>


		<!-- Comments
		================================================== -->
		<h3 class="headline">全部评论({{ item.comment }})<span class="comments-amount"></span></h3><span class="line"></span><div class="clearfix"></div>

			<!-- Reviews -->
			<section class="comments" id="reviews">

                    {% for i in comments %}
				<ul>


					<li>
						<div class="avatar"><img src="http://www.gravatar.com/avatar/00000000000000000000000000000000?d=mm&amp;s=70" alt="" /></div>
						<div class="comment-content" id="comment-content"><div class="arrow-comment"></div>
							<div class="comment-by"><strong>{{ i.comment_user.username }}</strong>&emsp;{{ i.comment_time|date:"Y-m-d H:i:s" }}
								<a href="#" class="reply"><i class="fa fa-reply"></i> 回复</a>
							</div>
							<p>{{ i.comment_text|safe }}</p>
						</div>

{#						<!-- Second Level -->#}
{#						<ul>#}
{#							<li>#}
{#								<div class="avatar"><img src="/static/images/author-photo.png" alt="" /></div>#}
{#								<div class="comment-content"><div class="arrow-comment"></div>#}
{#								<div class="comment-by"><strong>Sandra Fortin</strong><span class="date">7th, October 2014</span>#}
{#								<a href="#" class="reply"><i class="fa fa-reply"></i> Reply</a>#}
{#								</div>#}
{#								<p>Donec porttitor tortor sit amet tortor egestas, id suscipit magna cursus. Nam facilisis, mi vel elementum porttitor, sapien magna posuere lorem, sed consectetur.</p>#}
{#								</div>#}
{#							</li>#}
{#						</ul>#}

					</li>
                         </ul>
                    {% empty %}
                        暂无评论
                    {% endfor %}


			</section>
			<div class="clearfix"></div>
			<br>


		<!-- Add Comment
		================================================== -->

		<h3 class="headline">提交评论</h3><span class="line margin-bottom-35"></span><div class="clearfix"></div>

             <!-- Add Comment Form -->
		<form id="add-review" class="add-comment" action="" method="post" name="add_review">
        {% csrf_token %}
			<fieldset>
				<div class="clearfix"></div>
				<div>
					<label>用户<strong>{{ user }}</strong>,请输入评论内容: </label>
                    <input type="hidden" name="object_id" value="{{ item.id }}">
                    <input type="hidden" name="content_type" value="Item">
{#					<textarea cols="40" rows="3" name="text"></textarea>#}
                    {{ form.as_p }}

				</div>
			</fieldset>
{#			<a  class="button medium color" onclick="javascript:document.add_review.submit();">评论</a>#}

            <input type="submit" style="min-width: 40px;" value="评论" >

			<div class="clearfix"></div>
		</form>

		    <a href="{% url "user:login" %}" class="medium color">未登录?点击此处跳转至登录界面</a>
	</div>
     {% load static %}
    <script type="application/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="application/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script type="application/javascript">
        $("#add-review").submit(function(){
            CKEDITOR.instances["id_comment_text"].updateElement();
            //异步提交
            $.ajax({
                url: "{% url 'apis:comment' %}",
                type:'POST',
                data:$(this).serialize(),
                cache:false,
                success:function(data){
                    console.log(data);
                    if(data['status']=='SUCCESS'){
                    var comment_html = '<ul><li><div class="avatar"><img src="" alt="" /></div> ' +
                        '<div class="comment-content" id="comment-content"><div class="arrow-comment"></div>' +
                        '<div class="comment-by"><strong>'+data["comment_user"]+'</strong>&emsp;'+
                        data["comment_time"]+'<a href="#" class="reply"><i class="fa fa-reply"></i> 回复</a> </div> <p>'+
                        data["comment_text"]+'</p></div></li></ul>';
                    $('#reviews').prepend(comment_html);
                    CKEDITOR.instances["id_comment_text"].setData("");
                    }else{

                    }
                },
                error:function(xhr){
                    console.log(xhr);
                }

            });
            return false
        });
    </script>

{% endblock %}