apps/shop/cart/urls.py
from django.conf.urls import url
from apps.shop.cart import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'),  # 添加购物车数据
    url(r'^count/$', views.cart_count, name='count'),  # 获取用户购物车中商品的数量
]

apps/shop/urls.py
from django.conf.urls import url, include
from  .views import shop,detail
urlpatterns = [
    url(r'^$', shop, name='index'),
    url(r'^detail$', detail, name='detail'),
    url(r'^cart/', include('apps.shop.cart.urls', namespace='cart')), # 购物车模块
]

recipe/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from apps.user.views import submit,test
from apps.index.views import index,search,detail,add_collection
from apps.video.views import video
from apps.news.views import news
from apps.comment.views import community
from apps.shop.views import shop
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index,name='index'), # 首页
    url(r'^user/', include('apps.user.urls', namespace='user')), # 用户模块
    url(r'^shop/',include('apps.shop.urls',namespace='shop')), #商品模块

    url(r'^submit$',submit,name='submit'),

    url(r'^search/',search,name='search'),
    url(r'^detail/',detail,name='detail'),

    url(r'^video/',video,name='video'),

    url(r'^news/',news,name='news'),




    url(r'^add_collection$',add_collection,name='add_collection'),
    url(r'^test$',test,name='test'),
    url(r'^community/',community,name='community'),

    url('ckeditor',include('ckeditor_uploader.urls')),
    url(r'api/v1/',include('apps.apis.urls',namespace="apis")),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

apps/shop/cart/models.py
from django.db import models

# Create your models here.

apps/shop/models.py
from django.db import models
from utils.enums import *
from db.base_model import BaseModel

# Create your models here.
from lxml.etree import strip_tags

class ShopManager(models.Manager):
    '''商品模型管理器类'''
    # sort='new' 按照创建时间进行排序
    # sort='hot' 按照商品销量进行排序
    # sort='price' 按照商品的价格进行排序
    # sort= 按照默认顺序排序
    def get_shop_by_type(self,  limit=None, sort='default'):
        '''根据商品类型id查询商品信息'''
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-deal', )
        elif sort == 'price_asc':
            order_by = ('price', )
        elif sort == 'price_desc':
            order_by = ('-price', )
        else:
            order_by = ('-pk', ) # 按照primary key降序排列。

        # 查询数据
        shop_li = self.all().order_by(*order_by)

        # 查询结果集的限制
        if limit:
            shop_li = shop_li[:limit]
        return shop_li

    def get_shop_by_id(self, id):
        '''根据商品的id获取商品信息'''
        try:
            shop_item = self.get(id=id)
        except self.model.DoesNotExist:
            # 不存在商品信息
            shop_item = None
        return shop_item



class Shop(BaseModel):
    image = models.CharField(max_length=200,verbose_name="图片")
    price = models.CharField(max_length=20,verbose_name="商品价格")
    deal = models.CharField(max_length=20,verbose_name="商品销量")
    title = models.CharField(max_length=100,verbose_name="商品名称")
    shop = models.CharField(max_length=50,verbose_name="商店名称")
    location = models.CharField(max_length=50,verbose_name="商店地址")
    stock = models.IntegerField(default=100, verbose_name='商品库存')

    status_choices = ((k,v) for k,v in STATUS_CHOICE.items())
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

    objects = ShopManager()

    class Meta:
        verbose_name = "商品"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.excerpt:
            self.excerpt = strip_tags(self.title)[:50]

        super().save(*args, **kwargs)

apps/shop/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django_redis import get_redis_connection

from apps.shop.models import Shop


def cart_add(request):
    """向购物车添加数据"""
    shop_id = request.POST.get('shop_id')
    shop_count = request.POST.get('shop_count')
    print(shop_id,shop_count)
    #数据校验
    if not all([shop_id,shop_count]):
        return JsonResponse({"res":1,"errmsg":"数据不完整"})

    shop_item = Shop.objects.get_shop_by_id(id=shop_id)
    if shop_item is None:
        return JsonResponse({"res":2,"errmsg":"商品不存在"})

    try:
        count = int(shop_count)
    except Exception as e:
        return JsonResponse({"res":3,"errmsg":"商品必须为数字"})

    # 添加商品到购物车
    # 每个用户的购物车记录用一条hash数据保存，格式:cart_用户id: 商品id 商品数量
    conn =get_redis_connection('default')
    cart_key = f'cart_{request.user.id}'
    res = conn.hget(cart_key,shop_id)
    if res is None:
        res = count
    else:
        res = int(res) + count

    #判断商品的库存
    if res >= shop_item.stock:
        #库存不足
        return JsonResponse({"res":4,"errmsg":"商品库存不足"})
    else:
        conn.hset(cart_key,shop_id,res)
    return JsonResponse({"res":5})

def cart_count(request):
    """获取用户购物车中的商品数目"""
    conn = get_redis_connection('default')
    cart_key = f'cart_{request.user.id}'
    res = 0
    res_list = conn.hvals(cart_key)
    for i in res_list:
        res += int(i)
    return JsonResponse({"res":res})

apps/shop/views.py
import random

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django_redis import get_redis_connection

from .models import Shop
import json
from django.core import serializers
# Create your views here.
from django.views.decorators.cache import cache_page
@cache_page(60 * 15)
def shop(request):
    shop_new = Shop.objects.get_shop_by_type(limit=9,sort='new')
    shop_hot = Shop.objects.get_shop_by_type(limit=9,sort='hot')
    shop_price_asc = Shop.objects.get_shop_by_type(limit=9,sort='asc_price')
    shop_price_desc = Shop.objects.get_shop_by_type(limit=9,sort='desc_price')
    shop_items = Shop.objects.all()[:9]

    context = {
        'shop_new':shop_new,
        'shop_hot':shop_hot,
        'shop_price_asc':shop_price_asc,
        'shop_price_desc':shop_price_desc,
        'shop_items':shop_items,
    }
    return render(request,"shop.html",context)

def detail(request):
    id = request.GET.get("id","")
    shop_item = Shop.objects.get_shop_by_id(id)
    if shop_item is None:
        return redirect(reverse("shop:index"))

    #新品推荐
    shop_recommend = random.sample(list(Shop.objects.all()), 4)
    context = {
        "shop_item":shop_item,
        "shop_recommend":shop_recommend,
    }
    return render(request,'product-page.html',context)

apps/shop/templates/product-page.html
{% extends "base.html" %}
{% block body %}

<!-- Titlebar
================================================== -->
<section id="titlebar">
	<!-- Container -->
	<div class="container">

		<div class="eight columns">
			<h2>Shop</h2>
		</div>

		<div class="eight columns">
			<nav id="breadcrumbs">
				<ul>
					<li>你在:</li>
					<li><a href="{% url "index" %}">主页</a></li>
					<li><a href="{% url "shop:index" %}">商店</a></li>
					<li>商品详情</li>
				</ul>
			</nav>
		</div>

	</div>
	<!-- Container / End -->
</section>



<!-- Content
================================================== -->


<div class="container">

<!-- Slider
================================================== -->
	<div class="eight columns" >
		<!-- Slider -->
		<div class="productSlider rsDefault">
		    <img class="rsImg" src="{{ shop_item.image }}" alt="" />
		</div>
		<div class="clearfix"></div>
	</div>


<!-- Content
================================================== -->
	<div class="eight columns">
		<div class="product-page">

			<!-- Headline -->
			<section class="title">
				<h2>{{ shop_item.title }}</h2>
				<div class="product-price">{{shop_item.price}}</div>

			</section>

			<!-- Text Parapgraph -->
			<section>
                <p class="margin-reset"></p>

			</section>


			<section class="linking">

					<form action='#'>
                        {% csrf_token %}
						<div class="qtyminus"></div>
						<input type='text' name="quantity" value='1' class="qty" />
						<div class="qtyplus"></div>
					</form>
                    <div>
					<a href="javascript:;" class="button adc color" id="add_cart" shop_id="{{ shop_item.id }}">加入购物车</a>
                    <a href="#" class="button color adc" >立即购买</a>
                    </div>
					<div class="clearfix"></div>

			</section>
<script type="text/javascript">

    $('#add_cart').click(function(){
        // 获取商品的id和商品数量
        var shop_id = $(this).attr('shop_id');
        var shop_count = $('.qty').val();
        var csrf = $('input[name="csrfmiddlewaretoken"]').val();
        // 发起请求，访问/cart/add/, 进行购物车数据的添加
        var params = {
            'shop_id': shop_id,
            'shop_count': shop_count,
            'csrfmiddlewaretoken': csrf
        }


        $.post('/shop/cart/add/', params, function (data) {
            if (data.res == 5){
                // 添加成功
                alert("添加成功")
            } else {
                // 添加失败
                alert(data.errmsg)
            }
        })
    })
</script>

		</div>
	</div>

</div>


<div class="clearfix"></div>
<div class="margin-top-30"></div>


<div class="container">
	<div class="sixteen columns">
			<!-- Tabs Navigation -->
			<ul class="tabs-nav">
				<li class="active"><a href="#tab1">Item Description</a></li>
				<li><a href="#tab2">Additional Information</a></li>
				<li><a href="#tab3">Reviews <span class="tab-reviews">(0)</span></a></li>
			</ul>

			<!-- Tabs Content -->
			<div class="tabs-container">

				<div class="tab-content" id="tab1">
					<p>Lorem ipsum pharetra lorem felis. Aliquam egestas consectetur elementum class aptentea taciti sociosqu ad litora torquent perea conubia nostra lorem consectetur adipiscing elit. Donec vestibulum justo a diam ultricies pellentesque. Fusce vehicula libero arcu, vitae ornare turpis elementum at. Etiam posuere quam nec ligula dignissim iaculis donec eleifend laoreet ornare. Quisque mattis luctus est, a placerat elit pharetra.</p>
				</div>

				<div class="tab-content" id="tab2">

					<table class="basic-table">
						<tr>
							<th>Weight</th>
							<td>0.5 lbs</td>
						</tr>
					</table>

				</div>

				<div class="tab-content" id="tab3">

					<!-- Reviews -->
					<section class="comments reviews">
						<p class="margin-bottom-10">There are no reviews yet.</p>

						<a href="#small-dialog" class="popup-with-zoom-anim button color margin-left-0">Add Review</a>

						<div id="small-dialog" class="zoom-anim-dialog mfp-hide">
							<h3 class="headline">Add Review</h3><span class="line margin-bottom-25"></span><div class="clearfix"></div>

							<!-- Form -->
							<form id="add-comment" class="add-comment">
								<fieldset>

									<div>
										<label>Name:</label>
										<input type="text" value=""/>
									</div>

									<div>
										<label>Rating:</label>
										<span class="rate">
											<span class="star"></span>
											<span class="star"></span>
											<span class="star"></span>
											<span class="star"></span>
											<span class="star"></span>
										</span>
										<div class="clearfix"></div>
									</div>

									<div class="margin-top-20">
										<label>Email: <span>*</span></label>
										<input type="text" value=""/>
									</div>

									<div>
										<label>Review: <span>*</span></label>
										<textarea cols="40" rows="3"></textarea>
									</div>

								</fieldset>

								<a href="#" class="button color">Add Review</a>
								<div class="clearfix"></div>

							</form>
						</div>

					</section>

				</div>

			</div>
	</div>
</div>



<!-- Related Products -->
<div class="container margin-top-5">

	<!-- Headline -->
	<div class="sixteen columns">
		<h3 class="headline">推荐商品</h3>
		<span class="line margin-bottom-0"></span>
	</div>

	<!-- Products -->
	<div class="products">
        {% for i in shop_recommend %}
		<!-- Product #3 -->
		<div class="four columns">
			<figure class="product">

				<div class="mediaholder">
					<a href="{% url "shop:detail" %}?id={{ i.id }}">
						<img alt="" src="{{ i.image }}"/>
					</a>
					<a href="{% url "shop:detail" %}?id={{ i.id }}" class="product-button"><i class="fa fa-shopping-cart"></i></a>
				</div>

				<a href="product-page.html">
					<section>
						<div class="product-category">{{ i.shop }}</div>
						<h5>{{ i.title }}</h5>
						<div class="product-price">{{ i.price }}</div>
					</section>
				</a>
			</figure>
		</div>
        {% endfor %}


	</div>
</div>

<div class="margin-top-50"></div>


{% endblock %}
<!-- Wrapper / End -->

apps/shop/templates/shop.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
<section id="titlebar">
	<!-- Container -->
	<div class="container">

		<div class="eight columns">
			<h2>Shop</h2>
		</div>

		<div class="eight columns">
			<nav id="breadcrumbs">
				<ul>
					<li>你在:</li>
					<li><a href="#">主页</a></li>
					<li>商店</li>
				</ul>
			</nav>
		</div>

	</div>
	<!-- Container / End -->
</section>
<div class="container">

	<!-- Products -->
	<div class="twelve columns left-sidebar-class">

		<!-- Ordering -->
		<div class="ordering">
			<select class="chosen-select-no-single">
				<option value="menu_order" >默认排序</option>
				<option value="popularity" >按人气排序</option>
				<option value="rating" >按平均评级排序</option>
				<option value="date">按新旧程度排序</option>
				<option value="price" >按价格排序：从低到高</option>
				<option value="price-desc" >按价格排序：从高到低</option>
			</select>
		</div>
		<div class="clearfix"></div>

        {% for i in shop_items %}
		<!-- Product #1 -->
		<div class="four shop columns">
			<figure class="product">

				<div class="mediaholder">
					<a href="{% url "shop:detail" %}?id={{ i.id }}">
						<img alt="" src="{{ i.image }}"/>
					</a>
					<a href="{% url "shop:detail" %}?id={{ i.id }}" class="product-button"><i class="fa fa-shopping-cart"></i></a>
				</div>

				<a href="{% url "shop:detail" %}?id={{ i.id }}">
					<section>
						<div class="product-category">{{i.shop}}</div>
						<h5>{{i.title}}</h5>
						<div class="product-price">{{i.price}}</div>
					</section>
				</a>
			</figure>
		</div>
{% endfor %}


		<div class="clearfix"></div>
		<div class="margin-top-40"></div>

		<!-- Pagination -->
		<div class="pagination-container masonry">
			<nav class="pagination">
				<ul>
					<li><a href="#" class="current-page">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
				</ul>
			</nav>

			<nav class="pagination-next-prev">
				<ul>
					<li><a href="#" class="prev"></a></li>
					<li><a href="#" class="next"></a></li>
				</ul>
			</nav>
		</div>

	</div>


	<!-- Sidebar
	================================================== -->
	<div class="four columns">

		<!-- Search Form -->
		<div class="widget search-form">
			<nav class="search">
				<form action="#" method="get">
					<button><i class="fa fa-search"></i></button>
					<input class="search-field" type="text" placeholder="Search for products" value=""/>
				</form>
			</nav>
			<div class="clearfix"></div>
		</div>


		<!-- Cart -->
		<div class="widget">
			<h4 class="headline">购物车</h4>
			<span class="line margin-bottom-30"></span>
			<div class="clearfix"></div>

			<div class="widget_shopping_cart_content">
				<ul class="product_list_widget">

					<li>
						<a href="#" class="image"><img src="{{ shop_items.0.image }}" alt=""></a>
						<div class="product_title">
							<a href="#">{{shop_items.0.title}}</a>
							<div class="quantity">1 × <div class="amount">{{shop_items.0.price}}</div></div>
						</div>
					</li>

				</ul>

                <div class="total"><strong>总计:</strong><p class="amount">$2.99 </p>

				<div class="buttons">
					<a href="#" class="button">购物车</a>
					<a href="#" class="button color">支付</a>
				</div>
			</div>
		</div>


	 	<!-- Widget -->
	 	<div class="widget">
			<h4 class="headline">通过价格过滤</h4>
			<span class="line margin-bottom-30"></span>
			<div class="clearfix"></div>

			<div id="price-range">
				<div class="padding-range"><div id="slider-range"></div></div>
				<label for="amount">价格:</label>
				<input type="text" id="amount"/>
				<a href="#" class="button color">过滤</a>
			</div>
			<div class="clearfix"></div>
	 	</div>

	</div>

</div>
<!-- Container / End -->

</div>
<div class="margin-top-5"></div>
{# 获取用户购物车中商品的数目 #}
    <script>
    {#$.get('/shop/cart/count/', function (data) {#}
    {#            // {'res':商品的总数}#}
    {#            $('.product-price').html(data.res)#}
    {#)#}
    </script>
{% endblock %}