apps/user/urls.py
from django.conf.urls import url
from  .views import Register,user_login,user_logout
urlpatterns = [
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^register/$', Register.as_view(), name='register'),
]

recipe/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from apps.user.views import submit,test
from apps.index.views import index,search,detail,add_collection
from apps.video.views import video
from apps.news.views import news
from apps.comment.views import community
from apps.shop.views import shop
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index,name='index'), # 首页
    url(r'^user/', include('apps.user.urls', namespace='user')), # 用户模块
    url(r'^shop/',include('apps.shop.urls',namespace='shop')), #商品模块

    url(r'^submit$',submit,name='submit'),

    url(r'^search/',search,name='search'),
    url(r'^detail/',detail,name='detail'),

    url(r'^video/',video,name='video'),

    url(r'^news/',news,name='news'),




    url(r'^add_collection$',add_collection,name='add_collection'),
    url(r'^test$',test,name='test'),
    url(r'^community/',community,name='community'),

    url('ckeditor',include('ckeditor_uploader.urls')),
    url(r'api/v1/',include('apps.apis.urls',namespace="apis")),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

apps/comment/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from ckeditor.fields import RichTextField
# Create your models here.


class Comment(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    comment_text = RichTextUploadingField()
    comment_time = models.DateTimeField(auto_now_add=True)
    comment_user = models.ForeignKey(User, on_delete=models.DO_NOTHING)



    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        ordering = ['-id']

apps/comment/views.py
from django.shortcuts import render, redirect

from apps.comment.form import CommentText
from utils.decorators import login_required
from .models import Comment
from django.contrib.contenttypes.models import ContentType


# Create your views here.





# def comment(request):
#     # 判断用户是否登录
#     if not request.user.is_authenticated:
#         return error_response('没有登录，不能进行评论')
#     # 得到对应的评论内容（POST请求）
#     comment_text = request.POST['comment_text']
#     # 利用strip()函数去掉两边的空格，判断评论内容是否为空
#     if comment_text.strip() == '':
#         return error_response('评论内容为空')
#     else:
#         # 得到对应的数据
#         content_type = request.POST['content_type']
#         object_id = request.POST['object_id']
#         # 查询对应的ContentType对象和评论的对象是否存在
#         if (not ContentType.objects.filter(model=content_type).exists()) or (not Item.objects.filter(pk=object_id).exists()):
#             return error_response('评论对象不存在')
#         content_type = ContentType.objects.get(model=content_type)
#         # 创建评论
#         comment_data = Comment(content_type=content_type, object_id=object_id, comment_text=comment_text, comment_user=request.user)
#         comment_data.save()
#         # 得到评论的时间
#         comment_time = comment_data.comment_time.strftime('%Y-%m-%d %H:%M:%S')
#         return success_response(comment_text, request.user, comment_time)



@login_required
def community(request):
    user = request.user
    user_content_type = ContentType.objects.get_for_model(user)
    comments = Comment.objects.filter(content_type=user_content_type)[:10]
    form = CommentText()
    return render(request, "community.html", locals())

apps/comment/templates/community.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<section id="titlebar">
	<!-- Container -->
	<div class="container">

		<div class="eight columns">
			<h2>community</h2>
		</div>

		<div class="eight columns">
			<nav id="breadcrumbs">
				<ul>
					<li>你在:</li>
					<li><a href="{% url "index" %}">主页</a></li>
					<li>社区</li>
				</ul>
			</nav>
		</div>

	</div>
	<!-- Container / End -->
</section>
    <div class="container">

<h3 class="headline">最新评论<span class="comments-amount"></span></h3><span class="line"></span><div class="clearfix"></div>

			<!-- Reviews -->
			<section class="comments" id="reviews">
                {% for i in comments %}
				<ul>

					<li>
						<div class="avatar"><img src="" alt="" /></div>
						<div class="comment-content" id="comment-content"><div class="arrow-comment"></div>
							<div class="comment-by"><strong>{{ i.comment_user.username }}</strong>&emsp;{{ i.comment_time|date:"Y-m-d H:i:s" }}
								<a href="#" class="reply"><i class="fa fa-reply"></i> 回复</a>
							</div>
							<p>{{ i.comment_text|safe }}</p>
						</div>

{#						<!-- Second Level -->#}
{#						<ul>#}
{#							<li>#}
{#								<div class="avatar"><img src="/static/images/author-photo.png" alt="" /></div>#}
{#								<div class="comment-content"><div class="arrow-comment"></div>#}
{#								<div class="comment-by"><strong>Sandra Fortin</strong><span class="date">7th, October 2014</span>#}
{#								<a href="#" class="reply"><i class="fa fa-reply"></i> Reply</a>#}
{#								</div>#}
{#								<p>Donec porttitor tortor sit amet tortor egestas, id suscipit magna cursus. Nam facilisis, mi vel elementum porttitor, sapien magna posuere lorem, sed consectetur.</p>#}
{#								</div>#}
{#							</li>#}
{#						</ul>#}

					</li>

				 </ul>
                {% empty %}
                    暂无评论
                {% endfor %}
			</section>
			<div class="clearfix"></div>
			<br>



		<!-- Add Comment
		================================================== -->

		<h3 class="headline">提交评论</h3><span class="line margin-bottom-35"></span><div class="clearfix"></div>

             <!-- Add Comment Form -->
		<form id="add-review" class="add-comment" action="" method="post" name="add_review">
        {% csrf_token %}
			<fieldset>
				<div class="clearfix"></div>
				<div>
					<label>用户<strong>{{ user }}</strong>,请输入评论内容: <span>*</span></label>
                    <input type="hidden" name="object_id" value="{{ user.id }}">
                    <input type="hidden" name="content_type" value="User">
{#					<textarea cols="40" rows="3" name="text"></textarea>#}
                    {{ form.as_p }}

				</div>
			</fieldset>
{#			<a  class="button medium color" onclick="javascript:document.add_review.submit();">评论</a>#}

            <input type="submit" style="min-width: 40px;" value="评论" >

			<div class="clearfix"></div>
		</form>

		    <a href="{% url "user:login" %}" class="medium color">未登录?点击此处跳转至登录界面</a>

     <script type="application/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="application/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script type="application/javascript">
        $("#add-review").submit(function(){
            CKEDITOR.instances["id_comment_text"].updateElement();
            //异步提交
            $.ajax({
                url: "{% url 'apis:community' %}",
                type:'POST',
                data:$(this).serialize(),
                cache:false,
                success:function(data){
                    console.log(data);
                    if(data['status']=='SUCCESS'){
                    var comment_html = '<ul><li><div class="avatar"><img src="" alt="" /></div> ' +
                        '<div class="comment-content" id="comment-content"><div class="arrow-comment"></div>' +
                        '<div class="comment-by"><strong>'+data["comment_user"]+'</strong>&emsp;'+
                        data["comment_time"]+'<a href="#" class="reply"><i class="fa fa-reply"></i> 回复</a> </div> <p>'+
                        data["comment_text"]+'</p></div></li></ul>';
                    $('#reviews').prepend(comment_html);
                    CKEDITOR.instances["id_comment_text"].setData("");
                    }
                },
                error:function(xhr){
                    console.log(xhr);
                }

            });
            return false
        });
    </script>
</div>

{% endblock %}